vversion: "3.8"
services:
  rest:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.rest
    image: productivity-app-rest
    restart: always
    ports:
      - 8080:8080
    depends_on:
       - db
      db:
        condition: service_healthy
  db:
    image: postgres:13
    restart: always
    env_file:
      - ./db-creds.env
    environment:
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      start_period: 20s
      interval: 1m
      timeout: 5s
      retries: 5
volumes:
  db-data:
 
