host: smtp.yandex.com
port: 465
username: xeva-productivity
password: KAD$Kz>SoFb5N#AQ1?=9
from: xeva-productivity@yandex.com

properties:
  mail:
    smtp:
      auth: true
      ssl:
        enable: true
      socketFactory:
        port: 465
        class: javax.net.ssl.SSLSocketFactory
        fallback: false 
      connectiontimeout: 5000
      timeout: 3000
      writetimeout: 5000
