host: smtp.gmail.com
port: 465
username: productiveappdev@gmail.com
password: KAD$Kz>SoFb5N#AQ1?=91
from: productiveappdev@gmail.com
protocol: smtp

properties:
  mail:
    transport:
      protocol: smtp
    smtp:
      starttls:
        enable: true
      auth: true
      ssl:
        enable: true
      socketFactory:
        port: 465
        class: javax.net.ssl.SSLSocketFactory
        fallback: false
      connectiontimeout: 5000
      timeout: 3000
      writetimeout: 5000